/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.70
 * Generated at: 2024-03-27 03:11:46 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/standard.jar", Long.valueOf(1711337953129L));
    _jspx_dependants.put("jar:file:/C:/Jaemin_Seo/portfolio/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/mallwithjsp/WEB-INF/lib/standard.jar!/META-INF/c.tld", Long.valueOf(1098678690000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("	<meta charset=\"utf-8\">\r\n");
      out.write("	<title>미소 몰</title>\r\n");
      out.write("	<link href=\"css/main.css\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	<header>\r\n");
      out.write("		<div class=\"head\">\r\n");
      out.write("			<div class=\"upperHead\">\r\n");
      out.write("				<div id=\"logo\">\r\n");
      out.write("					<a href=\"#\">\r\n");
      out.write("						<img src=\"img/header/logo.png\" alt=\"한살림 장보기\">\r\n");
      out.write("					</a>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"login\">\r\n");
      out.write("					<ul class=\"myMenu\">\r\n");
      out.write("						<li class=\"dlvrMenu\">\r\n");
      out.write("							<a href=\"#\"><img src=\"img/header/icoDlvr.png\" alt=\"매장배달 바로가기\"></a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							");

								String userid = request.getParameter("userid");
								if (userid == null) {
							
      out.write("\r\n");
      out.write("									<a href=\"./login/loginform.jsp\">로그인</a>\r\n");
      out.write("							");

								} else {
							
      out.write("\r\n");
      out.write("									<a href=\"/mallwithjsp/manager.do?command=logout\">로그아웃</a>\r\n");
      out.write("							");

								}
							
      out.write("\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\">나의한살림</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=/mallwithjsp/manager.do?command=board_list>고객센터</a>\r\n");
      out.write("						</li>\r\n");
      out.write("						<li><a href=\"#\">매장안내</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div class=\"lowerHead\">\r\n");
      out.write("				<div class=\"category\">\r\n");
      out.write("					<button class=\"allProduct\" type=\"button\">\r\n");
      out.write("						<span>전체물품</span>\r\n");
      out.write("					</button>\r\n");
      out.write("					<ul class=\"categoryMain\">\r\n");
      out.write("						<li><a href=\"#\">추천</a></li>\r\n");
      out.write("						<li><a href=\"#\">알뜰</a></li>\r\n");
      out.write("						<li><a href=\"#\">새물품</a></li>\r\n");
      out.write("						<li><a href=\"#\">사전예약</a></li>\r\n");
      out.write("						<li><a href=\"#\">꼬마와땅</a></li>\r\n");
      out.write("						<li><a href=\"#\">채식</a></li>\r\n");
      out.write("						<li><a href=\"#\">참여</a></li>\r\n");
      out.write("					</ul>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"search\">\r\n");
      out.write("					<div class=\"searchCon\">\r\n");
      out.write("						<input type=\"search\" placeholder=\"무엇을 찾아드릴까요?\" id=\"searchKeyword\" value=\"\" maxlength=\"300\"\r\n");
      out.write("							onkeydown=\"searchKeydown();\">\r\n");
      out.write("						<button class=\"btnSearch\" type=\"button\" onclick=\"searchClick();\">\r\n");
      out.write("							<span class=\"hide\">검색</span>\r\n");
      out.write("						</button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</header>\r\n");
      out.write("\r\n");
      out.write("	<div id=\"contents\">\r\n");
      out.write("		<div class=\"slider\">\r\n");
      out.write("			<div class=\"mainVisual swipe-container\" style=\"height: 100%;\">\r\n");
      out.write("				<ul class=\"content\">\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/1월 꼬마와땅 유아식.jpg\" alt=\"1월 꼬마와땅 유아식\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/1월 이맘때이물품.jpg\" alt=\"1월 이맘때이물품\"></a>\r\n");
      out.write("					</li>1\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/1월 제철제맛 요리.jpg\" alt=\"1월 제철제맛 요리\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/2024 신규조합원 쿠폰 안내.jpg\" alt=\"2024 신규조합원 쿠폰 안내\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/24-1월 새해인사.jpg\" alt=\"24-1월 새해인사\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/24-1월 집중홍보물품 한입요거큐브.jpg\" alt=\"24-1월 집중홍보물품 한입요거큐브\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/겨울철 대표간식모음.jpg\" alt=\"겨울철 대표간식모음\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li class=\"swipe-slider\">\r\n");
      out.write("						<a href=\"#\"><img src=\"img/slider/조합원 채식밥상.jpg\" alt=\"조합원 채식밥상\"></a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("				<script src=\"/js/slide.js\"></script>\r\n");
      out.write("				<button type=\"button\" class=\"mainVisualPrev\"><span class=\"hide\">PREV</span></button>\r\n");
      out.write("				<button type=\"button\" class=\"mainVisualNext\"><span class=\"hide\">NEXT</span></button>\r\n");
      out.write("				<button type=\"button\" class=\"visual-stop play\"><span class=\"hide\">PLAY/STOP</span></button>\r\n");
      out.write("				<div class=\"mainVisualPag swipe-pagination-fraction\">\r\n");
      out.write("					<span class=\"slider-swipe-pagination-current\"></span>\r\n");
      out.write("					/\r\n");
      out.write("					<span class=\"slider-swipe-pagination-total\"></span>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"suggestion\">\r\n");
      out.write("			<div class=\"conArea\">\r\n");
      out.write("				<p class=\"mainTit\">이 물품은 어떠세요?</p>\r\n");
      out.write("				<div class=\"suggestionSwipe\">\r\n");
      out.write("					<div class=\"boxs\">\r\n");
      out.write("						<!-- JSON 데이터 읽어오기 -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"discount\">\r\n");
      out.write("			<div class=\"conArea\">\r\n");
      out.write("				<div class=\"conL\">\r\n");
      out.write("					<p class=\"mainTit\">\r\n");
      out.write("						<span>놓치기 아쉬운</span>\r\n");
      out.write("						<br>\r\n");
      out.write("						알뜰물품\r\n");
      out.write("					</p>\r\n");
      out.write("					<p class=\"txt\">\r\n");
      out.write("						가격인하 물품을\r\n");
      out.write("						<br>\r\n");
      out.write("						지금바로 이용해 보세요\r\n");
      out.write("					</p>\r\n");
      out.write("					<a href=\"#\" class=\"btnType btnSize34 btnColorGyL\">\r\n");
      out.write("						<span class=\"fc66\">더보기</span>\r\n");
      out.write("					</a>\r\n");
      out.write("					<div class=\"swipeNavType1\">\r\n");
      out.write("						<button class=\"swipeNavPrev\"></button>\r\n");
      out.write("						<div class=\"mainSalePag swipeNavPagination swipe-pagination-fraction\">\r\n");
      out.write("							<span class=\"swipe-pagination-current\">3</span>\r\n");
      out.write("							/\r\n");
      out.write("							<span class=\"swipe-pagination-total\">4</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"swipeNavNext\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"discountSwipe swipe-container\">\r\n");
      out.write("					<div class=\"boxs\">\r\n");
      out.write("						<!-- JSON 데이터 읽어오기 -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"new\">\r\n");
      out.write("			<div class=\"conArea\">\r\n");
      out.write("				<p class=\"mainTit\">\r\n");
      out.write("					<span>반가운</span>\r\n");
      out.write("					<br>\r\n");
      out.write("					새물품\r\n");
      out.write("				</p>\r\n");
      out.write("				<ul>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"imgWrap\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<img src=\"img/new/요거큐브.jpg\" alt=\"요거큐브\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<a href=\"#\">새콤달콤 유기농 딸기요구르트 과자, '한입요거큐브 딸기'</a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p class=\"txt\">\r\n");
      out.write("							<a href=\"#\">겉은 바삭, 입안에선 사르르~ 진한 맛은 물론 유산균도 풍부해요!</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"imgWrap\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<img src=\"img/new/요거큐브.jpg\" alt=\"요거큐브\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<a href=\"#\">새콤달콤 유기농 딸기요구르트 과자, '한입요거큐브 딸기'</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"imgWrap\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<img src=\"img/new/요거큐브.jpg\" alt=\"요거큐브\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<a href=\"#\">새콤달콤 유기농 딸기요구르트 과자, '한입요거큐브 딸기'</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"imgWrap\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<img src=\"img/new/요거큐브.jpg\" alt=\"요거큐브\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<a href=\"#\">새콤달콤 유기농 딸기요구르트 과자, '한입요거큐브 딸기'</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li>\r\n");
      out.write("						<div class=\"imgWrap\">\r\n");
      out.write("							<a href=\"#\">\r\n");
      out.write("								<img src=\"img/new/요거큐브.jpg\" alt=\"요거큐브\">\r\n");
      out.write("							</a>\r\n");
      out.write("						</div>\r\n");
      out.write("						<p class=\"tit\">\r\n");
      out.write("							<a href=\"#\">새콤달콤 유기농 딸기요구르트 과자, '한입요거큐브 딸기'</a>\r\n");
      out.write("						</p>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"recommend\">\r\n");
      out.write("			<div class=\"conArea\">\r\n");
      out.write("				<div class=\"conL\">\r\n");
      out.write("					<p class=\"mainTit\">\r\n");
      out.write("						<em class=\"fgGreen\">조합원</em>\r\n");
      out.write("						<span>님을 위한</span>\r\n");
      out.write("						<br>\r\n");
      out.write("						추천물품\r\n");
      out.write("					</p>\r\n");
      out.write("					<ul class=\"userTab\">\r\n");
      out.write("						<li>\r\n");
      out.write("							<a href=\"#\" class=\"active\">\r\n");
      out.write("								밥보다 더 많이 먹는 볶음 밑반찬\r\n");
      out.write("							</a>\r\n");
      out.write("						</li>\r\n");
      out.write("					</ul>\r\n");
      out.write("					<div class=\"swipeNavType1\">\r\n");
      out.write("						<button class=\"swipeNavPrev\"></button>\r\n");
      out.write("						<div class=\"mainSalePag swipeNavPagination swipe-pagination-fraction\">\r\n");
      out.write("							<span class=\"swipe-pagination-current\">1</span>\r\n");
      out.write("							/\r\n");
      out.write("							<span class=\"swipe-pagination-total\">4</span>\r\n");
      out.write("						</div>\r\n");
      out.write("						<button class=\"swipeNavNext\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"recommendSwipe swipe-container\">\r\n");
      out.write("					<div class=\"boxs\">\r\n");
      out.write("						<!-- JSON 데이터 읽어오기 -->\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"popular\">\r\n");
      out.write("			<div class=\"conArea\">\r\n");
      out.write("				<p class=\"mainTit\">\r\n");
      out.write("					<span>지금 가장 많이 이용하는</span>\r\n");
      out.write("					인기물품\r\n");
      out.write("				</p>\r\n");
      out.write("				<div class=\"productorTab\">\r\n");
      out.write("					<div\r\n");
      out.write("						class=\"mainProducerSwipe swipe-container swipe-container-initialized swipe-container-horizontal\">\r\n");
      out.write("						<div class=\"swipe-wrapper\">\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/쌀_잡곡.png')\"></em>쌀/잡곡\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260240934.png')\"></em>채소/버섯\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260252401.png')\"></em>과일/견과\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260267089.png')\"></em>축산/축산가공\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260282395.png')\"></em>수산/수산가공\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260298231.png')\"></em>반찬/양념/가루\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260311438.png')\"></em>식사대용/간편식\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em\r\n");
      out.write("											style=\"background-image:url('img/poppular/1628260323282.png')\"></em>간식/음료/유제품\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260332898.png')\"></em>건강/차\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em\r\n");
      out.write("											style=\"background-image:url('img/poppular/1628260346196.png')\"></em>화장품/오가닉코튼\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260430049.png')\"></em>주방/욕실/세정\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260440313.png')\"></em>휴지/생활\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260451878.png')\"></em>반려동물\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("							<div class=\"swipe-slide swipe-slide\" style=\"width: 140px; margin-right: 10px;\">\r\n");
      out.write("								<button type=\"button\" class=\"producerIco btnIco1\">\r\n");
      out.write("									<span>\r\n");
      out.write("										<em style=\"background-image:url('img/poppular/1628260461288.png')\"></em>대용량/어린이집\r\n");
      out.write("									</span>\r\n");
      out.write("								</button>\r\n");
      out.write("							</div>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("					<div class=\"swipeNavType1\">\r\n");
      out.write("						<button class=\"mainProducerPrev swipeNavPrev\"></button>\r\n");
      out.write("						<button class=\"mainProducerNext swipeNavNext\"></button>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"popularSwipe\">\r\n");
      out.write("					<!-- JSON 데이터 읽어오기 -->\r\n");
      out.write("				</div>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("	<footer>\r\n");
      out.write("		<div class=\"footerUtil\">\r\n");
      out.write("			<ul>\r\n");
      out.write("				<li><a href=\"\">이용약관</a></li>\r\n");
      out.write("				<li><a href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("				<li><a href=\"\">한살림소개</a></li>\r\n");
      out.write("				<li><a href=\"\">소식지PDF</a></li>\r\n");
      out.write("				<li><a href=\"\">앱다운로드</a></li>\r\n");
      out.write("			</ul>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"hssFamily\" style=\"display: none;\"></div>\r\n");
      out.write("		<div class=\"footerInfo\">\r\n");
      out.write("			<div class=\"infoWrap\">\r\n");
      out.write("				<div class=\"ftInfo\">\r\n");
      out.write("					<div class=\"box left\">\r\n");
      out.write("						<p>상호명 : 한살림소비자생활협동조합연합회</p>\r\n");
      out.write("						<p>대표자 : 권옥자</p>\r\n");
      out.write("						<p>사업자등록번호 : <a href=\"http://www.ftc.go.kr/bizCommPop.do?wrkr_no=1268212328&apv_perm_no=\"\r\n");
      out.write("								target=\"_blank\"><b>126-82-12328</b></a></p>\r\n");
      out.write("						<p>통신판매업신고번호 : <a href=\"http://www.ftc.go.kr/bizCommPop.do?wrkr_no=1268212328&apv_perm_no=\"\r\n");
      out.write("								target=\"_blank\"><b>2014-경기안성-093호</b></a></p>\r\n");
      out.write("						<p>안성사무소 : 경기 안성시 대덕면 안성대로 1526(보동리 285-3) / 서울사무소 : 서울시 강남구 봉은사로81길 15(삼성동)</p>\r\n");
      out.write("						<p>입점문의 : <a href=\"https://forms.gle/RSM8hTCxq23CuUAVA\" target=\"_blank\"><b>입점문의하기</b></a>\r\n");
      out.write("						</p>\r\n");
      out.write("						<p>이메일 : <a href=\"mailto:hansalim@hansalim.or.kr\">hansalim@hansalim.or.kr</a></p>\r\n");
      out.write("						<p>이곳의 모든 저작권은 한살림에게 있습니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<ul class=\"ftSns\">\r\n");
      out.write("					<li><a href=\"https://www.instagram.com/hansalim_official/\" target=\"_blank\"><span\r\n");
      out.write("								class=\"hide\">insta</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"https://www.facebook.com/hansalim1986\" target=\"_blank\"><span\r\n");
      out.write("								class=\"hide\">facebook</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("					<li><a href=\"http://blog.naver.com/hansalim\" target=\"_blank\"><span class=\"hide\">naver\r\n");
      out.write("								blog</span></a></li>\r\n");
      out.write("					<li><a href=\"https://www.youtube.com/channel/UCpu-ENJQUmzw1zgAKhwexag\" target=\"_blank\"><span\r\n");
      out.write("								class=\"hide\">youtube</span></a></li>\r\n");
      out.write("					<li><a href=\"https://pf.kakao.com/_biqNu\" target=\"_blank\"><span class=\"hide\">kakaotalk</span></a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</footer>\r\n");
      out.write("\r\n");
      out.write("	<script src=\"https://code.jquery.com/jquery-3.7.1.min.js\"\r\n");
      out.write("		integrity=\"sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=\" crossorigin=\"anonymous\"></script>\r\n");
      out.write("	<!-- 슬라이더 JS -->\r\n");
      out.write("	<script>\r\n");
      out.write("		function slide()\r\n");
      out.write("		{\r\n");
      out.write("			let wid = 1920;\r\n");
      out.write("			let arr = $('.swipe-slider').toArray();\r\n");
      out.write("			$('.slider-swipe-pagination-total').html(arr.length);\r\n");
      out.write("			arr.map((v, i) =>\r\n");
      out.write("			{\r\n");
      out.write("				$(v).attr('slider-index-data', i + 1);\r\n");
      out.write("			});\r\n");
      out.write("			$('.slider-swipe-pagination-current').html($('.content li:first-child').attr('slider-index-data'));\r\n");
      out.write("			function nextSlide()\r\n");
      out.write("			{\r\n");
      out.write("				if ($('.swipe-container .content').queue('fx').length === 0)\r\n");
      out.write("				{\r\n");
      out.write("					$('.content').stop(false, true).animate({ marginLeft: -wid }, 800, function ()\r\n");
      out.write("					{\r\n");
      out.write("						$('.swipe-container .content li:first-child').appendTo($('.swipe-container .content'));\r\n");
      out.write("						$('.swipe-container .content').css({ marginLeft: 0 });\r\n");
      out.write("						$('.slider-swipe-pagination-current').html($('.content li:first-child').attr('slider-index-data'));\r\n");
      out.write("					});\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			function prevSlide()\r\n");
      out.write("			{\r\n");
      out.write("				if ($('.swipe-container .content').queue('fx').length === 0)\r\n");
      out.write("				{\r\n");
      out.write("					$('.swipe-container .content li:last-child').prependTo('.content');\r\n");
      out.write("					$('.swipe-container .content').css({ marginLeft: -wid });\r\n");
      out.write("					$('.swipe-container .content').stop(false, true).animate({ marginLeft: 0 }, 800,);\r\n");
      out.write("					$('.slider-swipe-pagination-current').html($('.content li:first-child').attr('slider-index-data'));\r\n");
      out.write("				}\r\n");
      out.write("			};\r\n");
      out.write("			$('.mainVisualPrev').click(prevSlide);\r\n");
      out.write("			$('.mainVisualNext').click(nextSlide);\r\n");
      out.write("			let isStop = false;\r\n");
      out.write("			$('visual-stop').click(function ()\r\n");
      out.write("			{\r\n");
      out.write("				isStop = true;\r\n");
      out.write("				clearInterval(sliderIntervalIndex);\r\n");
      out.write("			});\r\n");
      out.write("			let sliderIntervalTime = 5000;\r\n");
      out.write("			let sliderIntervalIndex = setInterval(nextSlide, sliderIntervalTime);\r\n");
      out.write("			$('.slider').mouseover(function ()\r\n");
      out.write("			{\r\n");
      out.write("				clearInterval(sliderIntervalIndex);\r\n");
      out.write("			}).mouseleave(function ()\r\n");
      out.write("			{\r\n");
      out.write("				if (!isStop) sliderIntervalIndex = setInterval(nextSlide, sliderIntervalTime);\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("		slide();\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	</script>\r\n");
      out.write("	<!-- JSON 읽어오기 -->\r\n");
      out.write("	<script>\r\n");
      out.write("		// 상품 박스에 읽어온 JSON 데이터를 HTML 로 변환해서 string 으로 반환하는 함수\r\n");
      out.write("		function productBoxGenerator(data, containerSel)\r\n");
      out.write("		{\r\n");
      out.write("			const pasing = function (data)\r\n");
      out.write("			{\r\n");
      out.write("				let name = data.name;\r\n");
      out.write("				let price = data.price;\r\n");
      out.write("				price = price.toLocaleString();\r\n");
      out.write("				let pictureURL = data.pictureURL;\r\n");
      out.write("				let option = data.option;\r\n");
      out.write("				if (option === 'popular')\r\n");
      out.write("				{\r\n");
      out.write("					option = '<div><p class=\"pdtState\"><span>인기</span></p></div>';\r\n");
      out.write("				}\r\n");
      out.write("				else if (option === 'discount')\r\n");
      out.write("				{\r\n");
      out.write("					option = '<div><div class=\"pdtState list-type\"><p class=\"title\">알뜰</p><ul><li>가격인하</li></ul></div></div>';\r\n");
      out.write("				}\r\n");
      out.write("				let url = data.url;\r\n");
      out.write("				let text = '<a href=\"' + url + '\">' +\r\n");
      out.write("					'<div class=\"imgWrap\">' +\r\n");
      out.write("					option +\r\n");
      out.write("					'</p><img src=' + pictureURL + ' alt=\"' + name + '\">' +\r\n");
      out.write("					'</div><div class=\"textWrap\">' +\r\n");
      out.write("					'<p class=\"famousName\"><a href=\"#\">' + name + '</a></p>' +\r\n");
      out.write("					'<div class=\"famousPrice\">' +\r\n");
      out.write("					'<a href=\"' + url + '\">' +\r\n");
      out.write("					'<p class=\"price\">' + price + '<span>원</span></p>' +\r\n");
      out.write("					'</a>' +\r\n");
      out.write("					'</div>' +\r\n");
      out.write("					'<button class=\"btnCart\"></button>' +\r\n");
      out.write("					'</div>' +\r\n");
      out.write("					'</a >';\r\n");
      out.write("\r\n");
      out.write("				return text;\r\n");
      out.write("			};\r\n");
      out.write("			for (let i in data)\r\n");
      out.write("			{\r\n");
      out.write("				let text = pasing(data[i]);\r\n");
      out.write("				let container = $(containerSel);\r\n");
      out.write("				container.append('<div class=\"box\"></div>');\r\n");
      out.write("				container.children('.box').eq(i).append(text);\r\n");
      out.write("			}\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		//상품 슬라이드 함수\r\n");
      out.write("		function Productslide(conArea)\r\n");
      out.write("		{\r\n");
      out.write("			let wid = 912;\r\n");
      out.write("			let arr = $(conArea + '>.swipe-container>.boxs>.box').toArray();\r\n");
      out.write("			let content = conArea + '>.swipe-container>.boxs';\r\n");
      out.write("			let conNav = conArea + '>.conL>.swipeNavType1';\r\n");
      out.write("			let maxidx = Math.ceil(arr.length / 3);\r\n");
      out.write("			$(conNav + '>.mainSalePag>.swipe-pagination-total').text(maxidx);\r\n");
      out.write("			arr.map((v, i) =>\r\n");
      out.write("			{\r\n");
      out.write("				$(v).attr('slider-index-data', i + 1);\r\n");
      out.write("			});\r\n");
      out.write("			let index = 1;\r\n");
      out.write("			let currentMargin = 0;\r\n");
      out.write("			let boxidx = 3;\r\n");
      out.write("			$(conNav + '>.mainSalePag>.swipe-pagination-current').text(index);\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			function nextSlide()\r\n");
      out.write("			{\r\n");
      out.write("				let strArr = $(content).css('margin-left').split('');\r\n");
      out.write("				let num = strArr.splice(0, strArr.length - 2).join('');\r\n");
      out.write("				currentMargin = Number(num);\r\n");
      out.write("\r\n");
      out.write("				if ($(content).queue('fx').length !== 0)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (index === maxidx)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (arr.length - boxidx >= 3)\r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin - wid;\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx += 3;\r\n");
      out.write("				}\r\n");
      out.write("				else\r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin - ((wid / 3 * (arr.length % 3)));\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx = arr.length;\r\n");
      out.write("				}\r\n");
      out.write("				$(conNav + '>.mainSalePag>.swipe-pagination-current').text(String(++index));\r\n");
      out.write("			}\r\n");
      out.write("			function prevSlide()\r\n");
      out.write("			{\r\n");
      out.write("				let strArr = $(content).css('margin-left').split('');\r\n");
      out.write("				let num = strArr.splice(0, strArr.length - 2).join('');\r\n");
      out.write("				currentMargin = Number(num);\r\n");
      out.write("\r\n");
      out.write("				if ($(content).queue('fx').length !== 0)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (index === 1)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (boxidx - 3 >= 3)\r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin + wid;\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx -= 3;\r\n");
      out.write("				}\r\n");
      out.write("				else\r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin + ((wid / 3 * (arr.length % 3)));\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx = 3;\r\n");
      out.write("				}\r\n");
      out.write("				$(conNav + '>.mainSalePag>.swipe-pagination-current').text(String(--index));\r\n");
      out.write("			}\r\n");
      out.write("			$(conNav + '>.swipeNavPrev').mousedown(prevSlide);\r\n");
      out.write("			$(conNav + '>.swipeNavNext').mousedown(nextSlide);\r\n");
      out.write("		}\r\n");
      out.write("		//상품 탭 슬라이드 함수\r\n");
      out.write("		function Tabslide(conArea)\r\n");
      out.write("		{\r\n");
      out.write("			let wid = 1040;\r\n");
      out.write("			let arr = $('.swipe-slide').toArray();\r\n");
      out.write("			let content = '.swipe-wrapper';\r\n");
      out.write("			let currentMargin = 0;\r\n");
      out.write("			let boxidx = 0;\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("			function nextSlide()\r\n");
      out.write("			{\r\n");
      out.write("				let strArr = $(content).css('margin-left').split('');\r\n");
      out.write("				let num = strArr.splice(0, strArr.length - 2).join('');\r\n");
      out.write("				currentMargin = Number(num);\r\n");
      out.write("\r\n");
      out.write("				if ($(content).queue('fx').length !== 0)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (boxidx === 3)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else \r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin - wid;\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx += 3;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			function prevSlide()\r\n");
      out.write("			{\r\n");
      out.write("\r\n");
      out.write("				let strArr = $(content).css('margin-left').split('');\r\n");
      out.write("				let num = strArr.splice(0, strArr.length - 2).join('');\r\n");
      out.write("				currentMargin = Number(num);\r\n");
      out.write("\r\n");
      out.write("				if ($(content).queue('fx').length !== 0)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else if (boxidx === 0)\r\n");
      out.write("				{\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				else\r\n");
      out.write("				{\r\n");
      out.write("					currentMargin = currentMargin + wid;\r\n");
      out.write("					$(content).stop(false, true).animate({ marginLeft: currentMargin }, 800);\r\n");
      out.write("					boxidx -= 3;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("			$('.mainProducerPrev').mousedown(prevSlide);\r\n");
      out.write("			$('.mainProducerNext').mousedown(nextSlide);\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		$(function ()//메인 추천 구역\r\n");
      out.write("		{\r\n");
      out.write("			$.ajax(\r\n");
      out.write("				{\r\n");
      out.write("					url: \"./json/mainRecommandProduct.json\",\r\n");
      out.write("					dataType: \"json\",\r\n");
      out.write("					success: function (data)\r\n");
      out.write("					{\r\n");
      out.write("						productBoxGenerator(data, '.suggestion>.conArea>.suggestionSwipe>.boxs');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("		});\r\n");
      out.write("		$(function ()//세일 구역\r\n");
      out.write("		{\r\n");
      out.write("			$.ajax(\r\n");
      out.write("				{\r\n");
      out.write("					url: \"./json/discountProduct.json\",\r\n");
      out.write("					dataType: \"json\",\r\n");
      out.write("					success: function (data)\r\n");
      out.write("					{\r\n");
      out.write("						productBoxGenerator(data, '.discount>.conArea>.discountSwipe>.boxs');\r\n");
      out.write("						Productslide('.discount>.conArea');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("		});\r\n");
      out.write("		$(function ()//서브 추천 구역\r\n");
      out.write("		{\r\n");
      out.write("			$.ajax(\r\n");
      out.write("				{\r\n");
      out.write("					url: \"./json/recomendProduct.json\",\r\n");
      out.write("					dataType: \"json\",\r\n");
      out.write("					success: function (data)\r\n");
      out.write("					{\r\n");
      out.write("						productBoxGenerator(data, '.recommend>.conArea>.recommendSwipe>.boxs');\r\n");
      out.write("						Productslide('.recommend>.conArea');\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("		});\r\n");
      out.write("		$(function ()//인기 구역(버튼 누르면 다른 상품 뜨게 바꿔야함)\r\n");
      out.write("		{\r\n");
      out.write("			$.ajax(\r\n");
      out.write("				{\r\n");
      out.write("					url: \"./json/popularProduct.json\",\r\n");
      out.write("					dataType: \"json\",\r\n");
      out.write("					success: function (data)\r\n");
      out.write("					{\r\n");
      out.write("						let start = 0, end = 0;\r\n");
      out.write("						data.map((v, i) =>\r\n");
      out.write("						{\r\n");
      out.write("							if ((i + 1) % 4 === 0 && i !== 0)\r\n");
      out.write("							{\r\n");
      out.write("								end = i;\r\n");
      out.write("								let arr = data.slice(start, end + 1);\r\n");
      out.write("								let num = ((i + 1) / 4);\r\n");
      out.write("								$('.popularSwipe').append('<div class=\"boxs\"\"></div>');\r\n");
      out.write("								productBoxGenerator(arr, '.popularSwipe>.boxs:nth-child(' + num + ')');\r\n");
      out.write("								$('.popularSwipe>.boxs:nth-child(' + num + ')').css({ zIndex: 0 - num + 1 });\r\n");
      out.write("								start = end + 1;\r\n");
      out.write("							}\r\n");
      out.write("						});\r\n");
      out.write("						// productBoxGenerator(data, '.popular>.conArea>.popularSwipe>.boxs');\r\n");
      out.write("						Tabslide('.poppular>.conArea');\r\n");
      out.write("						let prevZ = 0;\r\n");
      out.write("						$('.swipe-wrapper>.swipe-slide').click(function ()\r\n");
      out.write("						{\r\n");
      out.write("							let num = $('.swipe-slide').index(this);\r\n");
      out.write("							$('.popularSwipe>.boxs').eq(num).css({ zIndex: 1 });\r\n");
      out.write("							$('.popularSwipe>.boxs').eq(0 - prevZ).css({ zIndex: prevZ });\r\n");
      out.write("							prevZ = 0 - num;\r\n");
      out.write("\r\n");
      out.write("							console.log(0 - prevZ, prevZ);\r\n");
      out.write("						});\r\n");
      out.write("					}\r\n");
      out.write("				});\r\n");
      out.write("		});\r\n");
      out.write("		$(function ()\r\n");
      out.write("		{\r\n");
      out.write("\r\n");
      out.write("		})\r\n");
      out.write("	</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
